import type { BookMeta } from "@/types/scripture";

export const BOOKS: BookMeta[] = [
  { name: "Genesis", slug: "genesis", aliases: ["genesis", "gen"] },
  { name: "Exodus", slug: "exodus", aliases: ["exodus", "exod", "ex"] },
  { name: "Leviticus", slug: "leviticus", aliases: ["leviticus", "lev"] },
  { name: "Numbers", slug: "numbers", aliases: ["numbers", "num"] },
  { name: "Deuteronomy", slug: "deuteronomy", aliases: ["deuteronomy", "deut"] },
  { name: "Joshua", slug: "joshua", aliases: ["joshua", "josh"] },
  { name: "Judges", slug: "judges", aliases: ["judges", "judg"] },
  { name: "Ruth", slug: "ruth", aliases: ["ruth"] },
  { name: "1 Samuel", slug: "1-samuel", aliases: ["1 samuel", "1 sam"] },
  { name: "2 Samuel", slug: "2-samuel", aliases: ["2 samuel", "2 sam"] },
  { name: "1 Kings", slug: "1-kings", aliases: ["1 kings", "1 kgs"] },
  { name: "2 Kings", slug: "2-kings", aliases: ["2 kings", "2 kgs"] },
  { name: "1 Chronicles", slug: "1-chronicles", aliases: ["1 chronicles", "1 chron"] },
  { name: "2 Chronicles", slug: "2-chronicles", aliases: ["2 chronicles", "2 chron"] },
  { name: "Ezra", slug: "ezra", aliases: ["ezra"] },
  { name: "Nehemiah", slug: "nehemiah", aliases: ["nehemiah", "neh"] },
  { name: "Esther", slug: "esther", aliases: ["esther", "esth"] },
  { name: "Job", slug: "job", aliases: ["job"] },
  { name: "Psalm", slug: "psalm", aliases: ["psalm", "psalms", "ps", "psa"] },
  { name: "Proverbs", slug: "proverbs", aliases: ["proverbs", "prov"] },
  { name: "Ecclesiastes", slug: "ecclesiastes", aliases: ["ecclesiastes", "eccl"] },
  { name: "Song of Solomon", slug: "song-of-solomon", aliases: ["song of solomon", "songofsolomon"] },
  { name: "Isaiah", slug: "isaiah", aliases: ["isaiah", "isa"] },
  { name: "Jeremiah", slug: "jeremiah", aliases: ["jeremiah", "jer"] },
  { name: "Lamentations", slug: "lamentations", aliases: ["lamentations", "lam"] },
  { name: "Ezekiel", slug: "ezekiel", aliases: ["ezekiel", "ezek"] },
  { name: "Daniel", slug: "daniel", aliases: ["daniel", "dan"] },
  { name: "Hosea", slug: "hosea", aliases: ["hosea", "hos"] },
  { name: "Joel", slug: "joel", aliases: ["joel"] },
  { name: "Amos", slug: "amos", aliases: ["amos"] },
  { name: "Obadiah", slug: "obadiah", aliases: ["obadiah", "obad"] },
  { name: "Jonah", slug: "jonah", aliases: ["jonah"] },
  { name: "Micah", slug: "micah", aliases: ["micah"] },
  { name: "Nahum", slug: "nahum", aliases: ["nahum"] },
  { name: "Habakkuk", slug: "habakkuk", aliases: ["habakkuk", "hab"] },
  { name: "Zephaniah", slug: "zephaniah", aliases: ["zephaniah", "zeph"] },
  { name: "Haggai", slug: "haggai", aliases: ["haggai", "hag"] },
  { name: "Zechariah", slug: "zechariah", aliases: ["zechariah", "zech"] },
  { name: "Malachi", slug: "malachi", aliases: ["malachi", "mal"] },
  { name: "Matthew", slug: "matthew", aliases: ["matthew", "matt"] },
  { name: "Mark", slug: "mark", aliases: ["mark"] },
  { name: "Luke", slug: "luke", aliases: ["luke"] },
  { name: "John", slug: "john", aliases: ["john"] },
  { name: "Acts", slug: "acts", aliases: ["acts"] },
  { name: "Romans", slug: "romans", aliases: ["romans", "rom"] },
  { name: "1 Corinthians", slug: "1-corinthians", aliases: ["1 corinthians", "1 cor"] },
  { name: "2 Corinthians", slug: "2-corinthians", aliases: ["2 corinthians", "2 cor"] },
  { name: "Galatians", slug: "galatians", aliases: ["galatians", "gal"] },
  { name: "Ephesians", slug: "ephesians", aliases: ["ephesians", "eph"] },
  { name: "Philippians", slug: "philippians", aliases: ["philippians", "phil"] },
  { name: "Colossians", slug: "colossians", aliases: ["colossians", "col"] },
  { name: "1 Thessalonians", slug: "1-thessalonians", aliases: ["1 thessalonians", "1 thess"] },
  { name: "2 Thessalonians", slug: "2-thessalonians", aliases: ["2 thessalonians", "2 thess"] },
  { name: "1 Timothy", slug: "1-timothy", aliases: ["1 timothy", "1 tim"] },
  { name: "2 Timothy", slug: "2-timothy", aliases: ["2 timothy", "2 tim"] },
  { name: "Titus", slug: "titus", aliases: ["titus"] },
  { name: "Philemon", slug: "philemon", aliases: ["philemon"] },
  { name: "Hebrews", slug: "hebrews", aliases: ["hebrews", "heb"] },
  { name: "James", slug: "james", aliases: ["james", "jas"] },
  { name: "1 Peter", slug: "1-peter", aliases: ["1 peter", "1 pet"] },
  { name: "2 Peter", slug: "2-peter", aliases: ["2 peter", "2 pet"] },
  { name: "1 John", slug: "1-john", aliases: ["1 john"] },
  { name: "2 John", slug: "2-john", aliases: ["2 john"] },
  { name: "3 John", slug: "3-john", aliases: ["3 john"] },
  { name: "Jude", slug: "jude", aliases: ["jude"] },
  { name: "Revelation", slug: "revelation", aliases: ["revelation", "rev"] }
];

export function findBookByInput(input: string) {
  const normalized = input.toLowerCase().replace(/\./g, "").replace(/\s+/g, " ").trim();
  return BOOKS.find((book) => book.aliases.includes(normalized)) ?? null;
}

export function getBookBySlug(slug: string) {
  return BOOKS.find((book) => book.slug === slug) ?? null;
}
